apiVersion: v1
kind: Service
metadata:
  name: service-service
spec:
  type: ClusterIP      # тип доступу до сервісу, ClusterIp - значення за замовчуванням і може бути пропущене
  ports:
    - port: 3000         # порт по якому можна звератись до сервісу
      targetPort: 3000 # порт контейнера
  selector:
    app: service